[package]
name = "proto-definitions"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
serde = { version = "1.0.210", features = ["derive"] }
serde_yaml = "0.9.34"

[lib]
crate-type = ["lib"]
