// Include the `out_dir.rs` file generated by build.rs to expose `DESCRIPTOR_PATH`
include!(concat!(env!("OUT_DIR"), "/out_dir.rs"));

pub mod messenger {
    tonic::include_proto!("messenger"); // This will include the generated code for messenger.proto
}

pub mod minioc {
    tonic::include_proto!("minioc"); // Generated code for minioc.proto
}

pub mod codeg {
    tonic::include_proto!("codeg"); // Generated code for codeg.proto
}

pub mod matching {
    tonic::include_proto!("matching"); // Generated code for matching.proto
}

pub mod parquetb {
    tonic::include_proto!("parquetb"); // Generated code for parquetb.proto
}

pub mod query {
    tonic::include_proto!("query"); // Generated code for query.proto
}

pub mod tenantm {
    tonic::include_proto!("tenantm"); // Generated code for tenantm.proto
}

pub mod transformer {
    tonic::include_proto!("transformer"); // Generated code for transformer.proto
}
